//! Shape-preserving 2×2 transfer matrices.
//!
//! This module provides two related representations:
//!
//! - [`TransferMatrix2`] is the public sampled-array representation returned by the
//!   transfer backend;
//! - [`Transfer2Entries`] is the internal algebraic representation used while
//!   evaluating value-only, first-order, and second-order transfer matrices.
//!
//! [`Transfer2Entries`] is generic over its scalar-entry representation. Its
//! entries may therefore be sampled arrays, first-order jets, or second-order
//! jets.
//!
//! Transfer matrices compose by ordinary matrix multiplication. If a new layer
//! matrix `L` is encountered in propagation order and state vectors satisfy
//!
//! ```text
//! ψ_right = L ψ_left,
//! ```
//!
//! then the accumulated matrix is updated as:
//!
//! ```text
//! M_total <- L M_total.
//! ```
//!
//! Layer-specific construction is implemented in the private [`layer`] module.

use std::ops::{Add, Mul, Neg, Sub};

use nalgebra::ComplexField;
use ndarray::{ArrayBase, Dimension, OwnedRepr};
use num_traits::{One, Zero};

use crate::{
    ComplexScalar, Polarisation,
    algebra::{
        ArrayJet0, ArrayJet1, ArrayJet2, ArrayJetBivariate1, ArrayJetBivariate2, ScalarAlgebra,
    },
    backend::{PlaneWaveEntries, isotropic::IsotropicLayerQuantities},
    input::CanonicalCoordinates,
    material::{ConstitutiveEvaluator, ConstitutiveLift},
};

/// Zero-order entry-wise transfer representation.
pub(crate) type Transfer2Jet0<C, D, P> = Transfer2Entries<ArrayJet0<C, D, P>>;

/// First-order entry-wise transfer representation.
pub(crate) type Transfer2Jet1<C, D, P> = Transfer2Entries<ArrayJet1<C, D, P>>;

/// Second-order entry-wise transfer representation.
pub(crate) type Transfer2Jet2<C, D, P> = Transfer2Entries<ArrayJet2<C, D, P>>;

/// Bivariate entrywise transfer representation
pub(crate) type Transfer2JetBivariate1<C, D, P> = Transfer2Entries<ArrayJetBivariate1<C, D, P>>;

/// Second-order bivariate entrywise transfer representation
pub(crate) type Transfer2JetBivariate2<C, D, P> = Transfer2Entries<ArrayJetBivariate2<C, D, P>>;

/// Internal algebraic representation of a 2×2 transfer matrix.
///
/// `A` may be:
///
/// - an owned sampled array;
/// - a first-order scalar jet;
/// - a second-order scalar jet.
///
/// All four entries must share the same sampled shape and derivative
/// representation.
#[derive(Clone, Debug, PartialEq)]
pub(crate) struct Transfer2Entries<A> {
    pub(super) m11: A,
    pub(super) m12: A,
    pub(super) m21: A,
    pub(super) m22: A,
}

impl<A> Transfer2Entries<A> {
    /// Construct an internal matrix from its four entries.
    pub(crate) fn new(m11: A, m12: A, m21: A, m22: A) -> Self {
        Self { m11, m12, m21, m22 }
    }

    /// Return entry `(1, 1)`.
    pub(crate) fn m11(&self) -> &A {
        &self.m11
    }

    /// Return entry `(1, 2)`.
    pub(crate) fn m12(&self) -> &A {
        &self.m12
    }

    /// Return entry `(2, 1)`.
    pub(crate) fn m21(&self) -> &A {
        &self.m21
    }

    /// Return entry `(2, 2)`.
    pub(crate) fn m22(&self) -> &A {
        &self.m22
    }

    /// Consume the matrix and return its entries in row-major order.
    pub(crate) fn into_parts(self) -> (A, A, A, A) {
        (self.m11, self.m12, self.m21, self.m22)
    }
}

impl<A> Transfer2Entries<A> {
    pub(crate) fn identity_like(source: &ArrayBase<OwnedRepr<A::Scalar>, A::Dimension>) -> Self
    where
        A: ScalarAlgebra + Clone,
        A::Scalar: ComplexField + One + Zero,
    {
        let zero = A::filled_constant_like(source, <A::Scalar as Zero>::zero());
        let one = A::filled_constant_like(source, <A::Scalar as One>::one());

        Self::new(one.clone(), zero.clone(), zero, one)
    }

    /// Multiply two matrices using the supplied scalar algebra.
    ///
    /// This computes `self * rhs`:
    ///
    /// ```text
    /// [a b] [e f]   [ae + bg  af + bh]
    /// [c d] [g h] = [ce + dg  cf + dh]
    /// ```
    ///
    /// When `A` is a jet representation, all matrix-product derivatives are
    /// generated by the scalar product and sum rules.
    pub(crate) fn multiply(&self, rhs: &Self) -> Self
    where
        A: ScalarAlgebra,
        A::Scalar: ComplexField,
        A::Dimension: Dimension,
    {
        let m11 = self
            .m11
            .multiply(&rhs.m11)
            .add(&self.m12.multiply(&rhs.m21));

        let m12 = self
            .m11
            .multiply(&rhs.m12)
            .add(&self.m12.multiply(&rhs.m22));

        let m21 = self
            .m21
            .multiply(&rhs.m11)
            .add(&self.m22.multiply(&rhs.m21));

        let m22 = self
            .m21
            .multiply(&rhs.m12)
            .add(&self.m22.multiply(&rhs.m22));

        Self::new(m11, m12, m21, m22)
    }

    /// Compute the determinant using the supplied scalar algebra.
    ///
    /// The determinant is:
    ///
    /// ```text
    /// det(M) = m11 m22 - m12 m21.
    /// ```
    pub(crate) fn determinant(&self) -> A
    where
        A: ScalarAlgebra,
        A::Scalar: ComplexField,
        A::Dimension: Dimension,
    {
        self.m11
            .multiply(&self.m22)
            .subtract(&self.m12.multiply(&self.m21))
    }

    pub(crate) fn from_layer(quantities: &IsotropicLayerQuantities<A>, thickness: &A) -> Self
    where
        A: ScalarAlgebra,
        A::Scalar: ComplexField + One,
        A::Dimension: Dimension,
    {
        let theta = quantities.kappa().multiply(thickness);

        let sin = theta.sin();
        let cos = theta.cos();

        let factor_over_kappa = quantities.factor().divide(quantities.kappa());

        let kappa_over_factor = quantities.kappa().divide(quantities.factor());

        Self::new(
            cos.clone(),
            sin.multiply(&factor_over_kappa)
                .scale(-<A::Scalar as One>::one()),
            sin.multiply(&kappa_over_factor),
            cos,
        )
    }
}

pub(crate) struct Transfer2ExteriorContext<A> {
    left_quantities: IsotropicLayerQuantities<A>,
    right_quantities: IsotropicLayerQuantities<A>,
}

impl<J> Transfer2ExteriorContext<J> {
    pub(super) fn new<E, M>(
        coordinates: &CanonicalCoordinates<J>,
        left_exterior: &M,
        right_exterior: &M,
        polarisation: Polarisation,
    ) -> Self
    where
        J: ScalarAlgebra + ConstitutiveLift<E, M> + Clone,
        J::Scalar: ComplexScalar,
        J::Dimension: Dimension,
        E: ConstitutiveEvaluator<J::Scalar, J::Dimension, M>,
    {
        let left_quantities =
            IsotropicLayerQuantities::evaluate::<E, M>(left_exterior, coordinates, polarisation);

        let right_quantities =
            IsotropicLayerQuantities::evaluate::<E, M>(right_exterior, coordinates, polarisation);

        Self {
            left_quantities,
            right_quantities,
        }
    }
}

impl<A> PlaneWaveEntries for Transfer2Entries<A> {
    type ExteriorContext = Transfer2ExteriorContext<A>;
}
