//! Shape-preserving 2×2 transfer matrices.
//!
//! This module provides two related representations:
//!
//! - [`TransferMatrix2`] is the public sampled-array representation returned by the
//!   transfer backend;
//! - [`Matrix2Entries`] is the internal algebraic representation used while
//!   evaluating value-only, first-order, and second-order transfer matrices.
//!
//! [`Matrix2Entries`] is generic over its scalar-entry representation. Its
//! entries may therefore be sampled arrays, first-order jets, or second-order
//! jets.
//!
//! Transfer matrices compose by ordinary matrix multiplication. If a new layer
//! matrix `L` is encountered in propagation order and state vectors satisfy
//!
//! ```text
//! ψ_right = L ψ_left,
//! ```
//!
//! then the accumulated matrix is updated as:
//!
//! ```text
//! M_total <- L M_total.
//! ```
//!
//! Layer-specific construction is implemented in the private [`layer`] module.

use std::ops::{Add, Mul, Neg, Sub};

use ndarray::{ArrayBase, Dimension, OwnedRepr};

use crate::{
    ComplexScalar,
    backend::{
        algebra::ScalarAlgebra,
        derivative::ChainRule,
        isotropic::IsotropicLayerQuantities,
        jet::{ArrayJet, ArrayJetFirst, Jet, JetFirst},
    },
};

/// First-order entry-wise scattering representation.
pub(crate) type Transfer2JetFirst<C, D> = Matrix2Entries<ArrayJetFirst<C, D>>;

impl<C, D: Dimension> Transfer2JetFirst<C, D> {
    pub(crate) fn from_parts(value: TransferMatrix2<C, D>, first: TransferMatrix2<C, D>) -> Self {
        let m11 = JetFirst::from_parts(value.m11, first.m11);
        let m12 = JetFirst::from_parts(value.m12, first.m12);
        let m21 = JetFirst::from_parts(value.m21, first.m21);
        let m22 = JetFirst::from_parts(value.m22, first.m22);
        Self::new(m11, m12, m21, m22)
    }
}

/// Second-order entry-wise scattering representation.
pub(crate) type Transfer2Jet<C, D> = Matrix2Entries<ArrayJet<C, D>>;

impl<C, D: Dimension> Transfer2Jet<C, D> {
    pub(crate) fn from_parts(
        value: TransferMatrix2<C, D>,
        first: TransferMatrix2<C, D>,
        second: TransferMatrix2<C, D>,
    ) -> Self {
        let m11 = Jet::from_parts(value.m11, first.m11, second.m11);
        let m12 = Jet::from_parts(value.m12, first.m12, second.m12);
        let m21 = Jet::from_parts(value.m21, first.m21, second.m21);
        let m22 = Jet::from_parts(value.m22, first.m22, second.m22);
        Self::new(m11, m12, m21, m22)
    }
}

/// Internal algebraic representation of a 2×2 transfer matrix.
///
/// `A` may be:
///
/// - an owned sampled array;
/// - a first-order scalar jet;
/// - a second-order scalar jet.
///
/// All four entries must share the same sampled shape and derivative
/// representation.
#[derive(Clone, Debug, PartialEq)]
pub(crate) struct Matrix2Entries<A> {
    pub(super) m11: A,
    pub(super) m12: A,
    pub(super) m21: A,
    pub(super) m22: A,
}

impl<A> Matrix2Entries<A> {
    /// Construct an internal matrix from its four entries.
    pub(crate) fn new(m11: A, m12: A, m21: A, m22: A) -> Self {
        Self { m11, m12, m21, m22 }
    }

    /// Return entry `(1, 1)`.
    pub(crate) fn m11(&self) -> &A {
        &self.m11
    }

    /// Return entry `(1, 2)`.
    pub(crate) fn m12(&self) -> &A {
        &self.m12
    }

    /// Return entry `(2, 1)`.
    pub(crate) fn m21(&self) -> &A {
        &self.m21
    }

    /// Return entry `(2, 2)`.
    pub(crate) fn m22(&self) -> &A {
        &self.m22
    }

    /// Consume the matrix and return its entries in row-major order.
    pub(crate) fn into_parts(self) -> (A, A, A, A) {
        (self.m11, self.m12, self.m21, self.m22)
    }
}

impl<A> Matrix2Entries<A> {
    pub(crate) fn identity_like<C, D>(source: &ArrayBase<OwnedRepr<C>, D>) -> Self
    where
        C: ComplexScalar,
        D: Dimension,
        A: ScalarAlgebra<C, D> + Clone,
    {
        let zero = A::constant_like(source, C::zero());
        let one = A::constant_like(source, C::one());

        Self::new(one.clone(), zero.clone(), zero, one)
    }

    /// Multiply two matrices using the supplied scalar algebra.
    ///
    /// This computes `self * rhs`:
    ///
    /// ```text
    /// [a b] [e f]   [ae + bg  af + bh]
    /// [c d] [g h] = [ce + dg  cf + dh]
    /// ```
    ///
    /// When `A` is a jet representation, all matrix-product derivatives are
    /// generated by the scalar product and sum rules.
    pub(crate) fn multiply<C, D>(&self, rhs: &Self) -> Self
    where
        C: ComplexScalar,
        D: Dimension,
        A: ScalarAlgebra<C, D>,
    {
        let m11 = self
            .m11
            .multiply(&rhs.m11)
            .add(&self.m12.multiply(&rhs.m21));

        let m12 = self
            .m11
            .multiply(&rhs.m12)
            .add(&self.m12.multiply(&rhs.m22));

        let m21 = self
            .m21
            .multiply(&rhs.m11)
            .add(&self.m22.multiply(&rhs.m21));

        let m22 = self
            .m21
            .multiply(&rhs.m12)
            .add(&self.m22.multiply(&rhs.m22));

        Self::new(m11, m12, m21, m22)
    }

    /// Compute the determinant using the supplied scalar algebra.
    ///
    /// The determinant is:
    ///
    /// ```text
    /// det(M) = m11 m22 - m12 m21.
    /// ```
    pub(crate) fn determinant<C, D>(&self) -> A
    where
        C: ComplexScalar,
        D: Dimension,
        A: ScalarAlgebra<C, D>,
    {
        self.m11
            .multiply(&self.m22)
            .subtract(&self.m12.multiply(&self.m21))
    }

    pub(crate) fn from_layer<C, D>(quantities: &IsotropicLayerQuantities<A>, thickness: A) -> Self
    where
        C: ComplexScalar,
        D: Dimension,
        A: ScalarAlgebra<C, D> + Clone,
    {
        let theta = quantities.kappa().multiply(&thickness);

        let sin = theta.sin();
        let cos = theta.cos();

        let factor_over_kappa = quantities.factor().divide(quantities.kappa());

        let kappa_over_factor = quantities.kappa().divide(quantities.factor());

        Self::new(
            cos.clone(),
            sin.multiply(&factor_over_kappa).scale(-C::one()),
            sin.multiply(&kappa_over_factor),
            cos,
        )
    }
}

impl<C, D> Matrix2Entries<ArrayJetFirst<C, D>>
where
    C: ComplexScalar,
    D: Dimension,
{
    pub(crate) fn chain_rule(self, rule: &ChainRule<ArrayBase<OwnedRepr<C>, D>>) -> Self {
        let (m11, m12, m21, m22) = self.into_parts();

        Self::new(
            m11.chain_rule(rule),
            m12.chain_rule(rule),
            m21.chain_rule(rule),
            m22.chain_rule(rule),
        )
    }
}

impl<C, D> Matrix2Entries<ArrayJet<C, D>>
where
    C: ComplexScalar,
    D: Dimension,
{
    pub(crate) fn chain_rule(self, rule: &ChainRule<ArrayBase<OwnedRepr<C>, D>>) -> Self {
        let (m11, m12, m21, m22) = self.into_parts();

        Self::new(
            m11.chain_rule(rule),
            m12.chain_rule(rule),
            m21.chain_rule(rule),
            m22.chain_rule(rule),
        )
    }
}

/// Public shape-preserving 2×2 transfer matrix.
///
/// Every entry has the same sampled dimension `D`. The type does not encode a
/// physical boundary convention; it represents only the backend's native
/// transfer matrix.
#[derive(Clone, Debug, PartialEq)]
pub struct TransferMatrix2<C, D>
where
    D: Dimension,
{
    m11: ArrayBase<OwnedRepr<C>, D>,
    m12: ArrayBase<OwnedRepr<C>, D>,
    m21: ArrayBase<OwnedRepr<C>, D>,
    m22: ArrayBase<OwnedRepr<C>, D>,
}

impl<C, D> TransferMatrix2<C, D>
where
    D: Dimension,
{
    /// Construct a 2×2 matrix from four equally shaped sampled entries.
    ///
    /// This constructor does not perform runtime shape validation in release
    /// builds. Internal callers must preserve the equal-shape invariant.
    pub fn new(
        m11: ArrayBase<OwnedRepr<C>, D>,
        m12: ArrayBase<OwnedRepr<C>, D>,
        m21: ArrayBase<OwnedRepr<C>, D>,
        m22: ArrayBase<OwnedRepr<C>, D>,
    ) -> Self {
        debug_assert_eq!(m11.raw_dim(), m12.raw_dim(),);

        debug_assert_eq!(m11.raw_dim(), m21.raw_dim(),);

        debug_assert_eq!(m11.raw_dim(), m22.raw_dim(),);

        Self { m11, m12, m21, m22 }
    }

    /// Return entry `(1, 1)`.
    pub fn m11(&self) -> &ArrayBase<OwnedRepr<C>, D> {
        &self.m11
    }

    /// Return entry `(1, 2)`.
    pub fn m12(&self) -> &ArrayBase<OwnedRepr<C>, D> {
        &self.m12
    }

    /// Return entry `(2, 1)`.
    pub fn m21(&self) -> &ArrayBase<OwnedRepr<C>, D> {
        &self.m21
    }

    /// Return entry `(2, 2)`.
    pub fn m22(&self) -> &ArrayBase<OwnedRepr<C>, D> {
        &self.m22
    }

    /// Consume the matrix and return its entries in row-major order.
    #[allow(clippy::type_complexity)]
    pub(crate) fn into_parts(
        self,
    ) -> (
        ArrayBase<OwnedRepr<C>, D>,
        ArrayBase<OwnedRepr<C>, D>,
        ArrayBase<OwnedRepr<C>, D>,
        ArrayBase<OwnedRepr<C>, D>,
    ) {
        (self.m11, self.m12, self.m21, self.m22)
    }

    /// Consume the public matrix and convert it into the internal algebraic
    /// representation.
    pub(crate) fn into_entries(self) -> Matrix2Entries<ArrayBase<OwnedRepr<C>, D>> {
        self.into()
    }
}

impl<C, D> TransferMatrix2<C, D>
where
    C: ComplexScalar,
    D: Dimension,
{
    /// Construct the zero matrix with the sampled shape of `shape_source`.
    pub fn zeros_like(shape_source: &ArrayBase<OwnedRepr<C>, D>) -> Self {
        let zero = shape_source.mapv(|_| C::zero());

        Self::new(zero.clone(), zero.clone(), zero.clone(), zero)
    }

    /// Construct the identity matrix with the sampled shape of `shape_source`.
    pub fn identity_like(shape_source: &ArrayBase<OwnedRepr<C>, D>) -> Self {
        let one = shape_source.mapv(|_| C::one());

        let zero = shape_source.mapv(|_| C::zero());

        Self::new(one.clone(), zero.clone(), zero, one)
    }

    /// Compute the determinant at every sampled point.
    pub fn determinant(&self) -> ArrayBase<OwnedRepr<C>, D> {
        self.m11.clone() * self.m22.view() - self.m12.clone() * self.m21.view()
    }

    /// Multiply every matrix entry by a sampled coefficient array.
    ///
    /// `values` must have the same sampled shape as the matrix entries.
    pub fn scale_by_array(&self, values: &ArrayBase<OwnedRepr<C>, D>) -> Self {
        Self::new(
            self.m11.clone() * values.view(),
            self.m12.clone() * values.view(),
            self.m21.clone() * values.view(),
            self.m22.clone() * values.view(),
        )
    }
}

impl<C, D> From<Matrix2Entries<ArrayBase<OwnedRepr<C>, D>>> for TransferMatrix2<C, D>
where
    D: Dimension,
{
    fn from(entries: Matrix2Entries<ArrayBase<OwnedRepr<C>, D>>) -> Self {
        let (m11, m12, m21, m22) = entries.into_parts();

        Self::new(m11, m12, m21, m22)
    }
}

impl<C, D> From<TransferMatrix2<C, D>> for Matrix2Entries<ArrayBase<OwnedRepr<C>, D>>
where
    D: Dimension,
{
    fn from(matrix: TransferMatrix2<C, D>) -> Self {
        let (m11, m12, m21, m22) = matrix.into_parts();

        Self::new(m11, m12, m21, m22)
    }
}

impl<C, D> Add for &TransferMatrix2<C, D>
where
    C: ComplexScalar,
    D: Dimension,
{
    type Output = TransferMatrix2<C, D>;

    fn add(self, rhs: Self) -> Self::Output {
        TransferMatrix2::new(
            self.m11.clone() + rhs.m11.view(),
            self.m12.clone() + rhs.m12.view(),
            self.m21.clone() + rhs.m21.view(),
            self.m22.clone() + rhs.m22.view(),
        )
    }
}

impl<C, D> Sub for &TransferMatrix2<C, D>
where
    C: ComplexScalar,
    D: Dimension,
{
    type Output = TransferMatrix2<C, D>;

    fn sub(self, rhs: Self) -> Self::Output {
        TransferMatrix2::new(
            self.m11.clone() - rhs.m11.view(),
            self.m12.clone() - rhs.m12.view(),
            self.m21.clone() - rhs.m21.view(),
            self.m22.clone() - rhs.m22.view(),
        )
    }
}

impl<C, D> Neg for &TransferMatrix2<C, D>
where
    C: ComplexScalar,
    D: Dimension,
{
    type Output = TransferMatrix2<C, D>;

    fn neg(self) -> Self::Output {
        TransferMatrix2::new(
            -self.m11.clone(),
            -self.m12.clone(),
            -self.m21.clone(),
            -self.m22.clone(),
        )
    }
}

impl<C, D> Mul for &TransferMatrix2<C, D>
where
    C: ComplexScalar,
    D: Dimension,
{
    type Output = TransferMatrix2<C, D>;

    fn mul(self, rhs: Self) -> Self::Output {
        TransferMatrix2::new(
            self.m11.clone() * rhs.m11.view() + self.m12.clone() * rhs.m21.view(),
            self.m11.clone() * rhs.m12.view() + self.m12.clone() * rhs.m22.view(),
            self.m21.clone() * rhs.m11.view() + self.m22.clone() * rhs.m21.view(),
            self.m21.clone() * rhs.m12.view() + self.m22.clone() * rhs.m22.view(),
        )
    }
}

impl<C, D> Mul<C> for &TransferMatrix2<C, D>
where
    C: ComplexScalar,
    D: Dimension,
{
    type Output = TransferMatrix2<C, D>;

    fn mul(self, rhs: C) -> Self::Output {
        TransferMatrix2::new(
            self.m11.clone() * rhs,
            self.m12.clone() * rhs,
            self.m21.clone() * rhs,
            self.m22.clone() * rhs,
        )
    }
}

#[cfg(test)]
mod tests {
    use approx::assert_relative_eq;
    use ndarray::{Array0, Array1, arr0, array};
    use num_complex::Complex64;

    use super::*;

    use crate::backend::jet::{ArrayJet, ArrayJetFirst};

    type C = Complex64;

    fn c(value: f64) -> C {
        C::new(value, 0.0)
    }

    fn assert_complex_close(actual: C, expected: C, tolerance: f64) {
        assert_relative_eq!(
            actual.re,
            expected.re,
            epsilon = tolerance,
            max_relative = tolerance,
        );

        assert_relative_eq!(
            actual.im,
            expected.im,
            epsilon = tolerance,
            max_relative = tolerance,
        );
    }

    fn assert_array1_close(actual: &Array1<C>, expected: &Array1<C>, tolerance: f64) {
        assert_eq!(actual.raw_dim(), expected.raw_dim(),);

        for (&actual, &expected) in actual.iter().zip(expected.iter()) {
            assert_complex_close(actual, expected, tolerance);
        }
    }

    fn scalar_matrix(m11: f64, m12: f64, m21: f64, m22: f64) -> TransferMatrix2<C, ndarray::Ix0> {
        TransferMatrix2::new(arr0(c(m11)), arr0(c(m12)), arr0(c(m21)), arr0(c(m22)))
    }

    #[test]
    fn public_matrix_accessors_return_entries() {
        let matrix = scalar_matrix(1.0, 2.0, 3.0, 4.0);

        assert_eq!(matrix.m11()[()], c(1.0));
        assert_eq!(matrix.m12()[()], c(2.0));
        assert_eq!(matrix.m21()[()], c(3.0));
        assert_eq!(matrix.m22()[()], c(4.0));
    }

    #[test]
    fn public_matrix_identity_has_expected_entries() {
        let shape = arr0(c(7.0));

        let identity = TransferMatrix2::identity_like(&shape);

        assert_eq!(identity.m11()[()], c(1.0));
        assert_eq!(identity.m12()[()], c(0.0));
        assert_eq!(identity.m21()[()], c(0.0));
        assert_eq!(identity.m22()[()], c(1.0));
    }

    #[test]
    fn public_matrix_zero_has_expected_entries() {
        let shape = arr0(c(7.0));

        let zero = TransferMatrix2::zeros_like(&shape);

        assert_eq!(zero.m11()[()], c(0.0));
        assert_eq!(zero.m12()[()], c(0.0));
        assert_eq!(zero.m21()[()], c(0.0));
        assert_eq!(zero.m22()[()], c(0.0));
    }

    #[test]
    fn public_matrix_multiplication_matches_hand_calculation() {
        let left = scalar_matrix(1.0, 2.0, 3.0, 4.0);

        let right = scalar_matrix(5.0, 6.0, 7.0, 8.0);

        let product = &left * &right;

        assert_eq!(product.m11()[()], c(19.0));
        assert_eq!(product.m12()[()], c(22.0));
        assert_eq!(product.m21()[()], c(43.0));
        assert_eq!(product.m22()[()], c(50.0));
    }

    #[test]
    fn public_matrix_determinant_matches_hand_calculation() {
        let matrix = scalar_matrix(2.0, 3.0, 5.0, 7.0);

        assert_eq!(matrix.determinant()[()], c(-1.0),);
    }

    #[test]
    fn sampled_public_matrix_multiplication_preserves_shape() {
        let left = TransferMatrix2::new(
            array![c(1.0), c(2.0)],
            array![c(3.0), c(4.0)],
            array![c(5.0), c(6.0)],
            array![c(7.0), c(8.0)],
        );

        let right = TransferMatrix2::new(
            array![c(2.0), c(3.0)],
            array![c(4.0), c(5.0)],
            array![c(6.0), c(7.0)],
            array![c(8.0), c(9.0)],
        );

        let product = &left * &right;

        assert_eq!(product.m11().raw_dim(), left.m11().raw_dim(),);

        assert_array1_close(product.m11(), &array![c(20.0), c(34.0)], 1e-12);

        assert_array1_close(product.m12(), &array![c(28.0), c(46.0)], 1e-12);

        assert_array1_close(product.m21(), &array![c(52.0), c(74.0)], 1e-12);

        assert_array1_close(product.m22(), &array![c(76.0), c(102.0)], 1e-12);
    }

    #[test]
    fn public_and_internal_matrix_conversions_round_trip() {
        let original = scalar_matrix(1.0, 2.0, 3.0, 4.0);

        let entries: Matrix2Entries<Array0<C>> = original.clone().into();

        let recovered: TransferMatrix2<C, ndarray::Ix0> = entries.into();

        assert_eq!(recovered, original);
    }

    #[test]
    fn internal_matrix_multiplication_matches_public_multiplication() {
        let left = scalar_matrix(1.0, 2.0, 3.0, 4.0);

        let right = scalar_matrix(5.0, 6.0, 7.0, 8.0);

        let expected = &left * &right;

        let left_entries: Matrix2Entries<Array0<C>> = left.into();

        let right_entries: Matrix2Entries<Array0<C>> = right.into();

        let actual = left_entries.multiply::<C, _>(&right_entries);

        let actual: TransferMatrix2<C, ndarray::Ix0> = actual.into();

        assert_eq!(actual, expected);
    }

    #[test]
    fn internal_determinant_matches_public_determinant() {
        let matrix = scalar_matrix(2.0, 3.0, 5.0, 7.0);

        let expected = matrix.determinant();

        let entries: Matrix2Entries<Array0<C>> = matrix.into();

        let actual = entries.determinant::<C, _>();

        assert_eq!(actual, expected);
    }

    #[test]
    fn first_order_matrix_multiplication_uses_product_rule() {
        let left = Matrix2Entries::new(
            ArrayJetFirst::from_parts(arr0(c(2.0)), arr0(c(3.0))),
            ArrayJetFirst::constant(arr0(c(0.0))),
            ArrayJetFirst::constant(arr0(c(0.0))),
            ArrayJetFirst::constant(arr0(c(1.0))),
        );

        let right = Matrix2Entries::new(
            ArrayJetFirst::from_parts(arr0(c(5.0)), arr0(c(7.0))),
            ArrayJetFirst::constant(arr0(c(0.0))),
            ArrayJetFirst::constant(arr0(c(0.0))),
            ArrayJetFirst::constant(arr0(c(1.0))),
        );

        let product = left.multiply::<C, _>(&right);

        // (2 × 5)' = 3 × 5 + 2 × 7 = 29.
        assert_eq!(product.m11().value()[()], c(10.0),);

        assert_eq!(product.m11().first()[()], c(29.0),);
    }

    #[test]
    fn second_order_matrix_multiplication_uses_second_product_rule() {
        let left = Matrix2Entries::new(
            ArrayJet::from_parts(arr0(c(2.0)), arr0(c(3.0)), arr0(c(11.0))),
            ArrayJet::constant(arr0(c(0.0))),
            ArrayJet::constant(arr0(c(0.0))),
            ArrayJet::constant(arr0(c(1.0))),
        );

        let right = Matrix2Entries::new(
            ArrayJet::from_parts(arr0(c(5.0)), arr0(c(7.0)), arr0(c(13.0))),
            ArrayJet::constant(arr0(c(0.0))),
            ArrayJet::constant(arr0(c(0.0))),
            ArrayJet::constant(arr0(c(1.0))),
        );

        let product = left.multiply::<C, _>(&right);

        // (uv)'' = u''v + 2u'v' + uv''
        //          = 11×5 + 2×3×7 + 2×13
        //          = 123.
        assert_eq!(product.m11().value()[()], c(10.0),);

        assert_eq!(product.m11().first()[()], c(29.0),);

        assert_eq!(product.m11().second()[()], c(123.0),);
    }

    #[test]
    fn multiplication_order_is_not_commutative() {
        let left = scalar_matrix(1.0, 2.0, 0.0, 1.0);

        let right = scalar_matrix(1.0, 0.0, 3.0, 1.0);

        let left_then_right = &left * &right;
        let right_then_left = &right * &left;

        assert_ne!(left_then_right, right_then_left,);
    }
}
