[package]
name = "lamina-core"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Christopher R. Gubbin <cgubbin@gmail.com>"]
description = "Transfer- and scattering-matrix methods for planar electromagnetic systems"
categories = ["science", "mathematics"]
keywords = ["optics", "photonics", "electromagnetics", "transfer-matrix", "scattering-matrix"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/cgubbin/lamina-core/"
homepage = "https://github.com/cgubbin/lamina-core/"
readme = "README.md"

[lib]
name = "lamina_core"
path = "src/lib.rs"


[dependencies]
itertools = "0.15.0"
nalgebra = "0.33.3"
ndarray = "0.17.2"
num-complex = "0.4.6"
num-traits = "0.2.19"
thiserror = "2.0.18"
lamina-units = {path = "../lamina-units"}

[dev-dependencies]
approx = { version = "0.5.1", features = ["num-complex"] }


[profile.dev]
debug = true

[profile.release]
codegen-units = 1
lto = "thin"

[workspace.metadata.release]
tag = true
push = true
publish = true
sign-commit = false

[features]
