[package]
name = "tmm-core"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Rust project template with library and binary"
license = "MIT"

[lib]
name = "tmm_core"
path = "src/lib.rs"


[dependencies]
either = "1.16.0"
nalgebra = "0.33.3"
ndarray = "0.17.2"
num-complex = "0.4.6"
num-traits = "0.2.19"
thiserror = "2.0.18"

[dev-dependencies]
approx = { version = "0.5.1", features = ["num-complex"] }


[profile.dev]
debug = true

[profile.release]
codegen-units = 1
lto = "thin"

[workspace.metadata.release]
tag = true
push = true
publish = true
sign-commit = false

[features]
