//! Stack-level scalar 2×2 scattering backend.
//!
//! This module constructs the scattering response of an isotropic planar stack
//! from a sequence of:
//!
//! - interfaces between adjacent media;
//! - propagation sections through finite layers.
//!
//! If the stack is
//!
//! ```text
//! left exterior | layer 0 | layer 1 | ... | right exterior,
//! ```
//!
//! the physical cascade is:
//!
//! ```text
//! interface(left exterior, layer 0)
//! propagation(layer 0)
//! interface(layer 0, layer 1)
//! propagation(layer 1)
//! ...
//! interface(last layer, right exterior).
//! ```
//!
//! An empty stack therefore contains one interface directly between its two
//! exterior media.
//!
//! # Derivatives
//!
//! Spectral derivatives are evaluated first with respect to the backend's
//! primitive squared coordinates:
//!
//! ```text
//! k₀²
//! k∥².
//! ```
//!
//! The complete scattering cascade is then transformed to a requested linear
//! coordinate using the exact chain rule.
//!
//! Thickness derivatives affect only propagation through the requested finite
//! layer. Interface admittances have no explicit thickness dependence.
//!
//! Scattering derivatives are carried entrywise using scalar jets. The
//! Redheffer cascade is evaluated over those jets, so product, quotient, and
//! second-order derivative rules are generated by the common scalar algebra.

use ndarray::{ArrayBase, Dimension, OwnedRepr};

use crate::{
    ComplexScalar, DerivativeVariable, IncidentSide,
    backend::{
        PlanarInput,
        algebra::ScalarAlgebra,
        field::{
            BidirectionalWavesGeneric, InternalFieldRequest, LayerBoundaryWavesGeneric,
            PlaneWaveFieldResponse, PlaneWaveInternalFields,
        },
        isotropic::{
            IsotropicLayerAdmittance, IsotropicLayerFirstDerivatives, IsotropicLayerQuantities,
            IsotropicLayerSecondDerivatives,
        },
        jet::{ArrayJet, ArrayJetFirst},
        scatter2::{
            ScatterMatrix2,
            component::{interface, propagation_from_exponent},
            entries::{Scatter2Jet, Scatter2JetFirst, ScatterEntries, cascade},
            error::Scatter2Error,
        },
    },
    material::Material,
    stack::Stack,
};

/// Scalar-channel isotropic 2×2 scattering backend.
#[derive(Copy, Clone, Debug, Default)]
pub struct Scatter2;

impl Scatter2 {
    /// Construct a scattering backend.
    pub const fn new() -> Self {
        Self
    }

    /// Evaluate the native scattering matrix without derivatives.
    pub(crate) fn evaluate<M, C, D>(
        &self,
        stack: &Stack<M, C::RealField>,
        input: &PlanarInput<ArrayBase<OwnedRepr<C>, D>>,
        request: InternalFieldRequest,
    ) -> Result<ScatterMatrix2<C, D>, Scatter2Error>
    where
        M: Material<Real = C::RealField>,
        C: ComplexScalar,
        C::RealField: Copy,
        D: Dimension,
    {
        type Samples<C, D> = ArrayBase<OwnedRepr<C>, D>;

        let mut workspace: ScatterWorkspace<Samples<C, D>> =
            ScatterWorkspace::new(input.vacuum_wavenumber(), request, stack.len());

        // let mut total: ScatterEntries<Samples<C, D>> =
        //     ScatterEntries::identity_like(input.vacuum_wavenumber());

        let left_quantities = IsotropicLayerQuantities::new(stack.left_exterior(), input);

        let mut current_admittance = left_quantities.admittance().into_inner();

        for layer in stack.iter() {
            let quantities = IsotropicLayerQuantities::new(layer.material(), input);

            let layer_admittance = quantities.admittance().into_inner();

            let interface = interface::<C, D, _>(&current_admittance, &layer_admittance);

            let distance = C::from_real(layer.thickness().as_cm());

            let exponent = quantities.kappa().scale(C::i() * distance);

            let propagation = propagation_from_exponent::<C, D, _>(exponent);

            workspace.append_layer::<C, D>(interface, propagation);

            current_admittance = layer_admittance;
        }

        let right_quantities = IsotropicLayerQuantities::new(stack.right_exterior(), input);

        let right_admittance = right_quantities.admittance().into_inner();

        let final_interface = interface::<C, D, _>(&current_admittance, &right_admittance);

        workspace.append(final_interface);

        let total = workspace.into_total();

        Ok(ScatterMatrix2::from_entries(total))
    }

    /// Evaluate the scattering matrix and its first derivative.
    pub(crate) fn evaluate_first<M, C, D>(
        &self,
        stack: &Stack<M, C::RealField>,
        input: &PlanarInput<ArrayBase<OwnedRepr<C>, D>>,
        variable: DerivativeVariable,
        request: InternalFieldRequest,
    ) -> Result<Scatter2JetFirst<C, D>, Scatter2Error>
    where
        M: Material<Real = C::RealField>,
        C: ComplexScalar,
        C::RealField: Copy,
        D: Dimension,
    {
        validate_derivative_variable(stack, variable)?;

        let primitive = variable.primitive();

        let mut workspace = ScatterWorkspace::new(input.vacuum_wavenumber(), request, stack.len());

        let left_quantities = IsotropicLayerQuantities::new(stack.left_exterior(), input);

        let (_, mut current_admittance) =
            medium_first_jets(stack.left_exterior(), &left_quantities, input, primitive);

        for (index, layer) in stack.iter().enumerate() {
            let quantities = IsotropicLayerQuantities::new(layer.material(), input);

            let (kappa, layer_admittance) =
                medium_first_jets(layer.material(), &quantities, input, primitive);

            let interface = interface::<C, D, _>(&current_admittance, &layer_admittance);

            let exponent = first_propagation_exponent(
                &quantities,
                &kappa,
                layer.thickness().as_cm(),
                primitive,
                index,
            );

            let propagation = propagation_from_exponent::<C, D, _>(exponent);

            workspace.append_layer::<C, D>(interface, propagation);

            current_admittance = layer_admittance;
        }

        let right_quantities = IsotropicLayerQuantities::new(stack.right_exterior(), input);

        let (_, right_admittance) =
            medium_first_jets(stack.right_exterior(), &right_quantities, input, primitive);

        let final_interface = interface::<C, D, _>(&current_admittance, &right_admittance);

        workspace.append(final_interface);

        let mut total = workspace.into_total();

        if let Some(rule) = variable.chain_rule(input) {
            total = total.chain_rule(&rule);
        }

        Ok(total)
    }

    /// Evaluate the scattering matrix and its first two derivatives.
    pub(crate) fn evaluate_second<M, C, D>(
        &self,
        stack: &Stack<M, C::RealField>,
        input: &PlanarInput<ArrayBase<OwnedRepr<C>, D>>,
        variable: DerivativeVariable,
        request: InternalFieldRequest,
    ) -> Result<Scatter2Jet<C, D>, Scatter2Error>
    where
        M: Material<Real = C::RealField>,
        C: ComplexScalar,
        C::RealField: Copy,
        D: Dimension,
    {
        validate_derivative_variable(stack, variable)?;

        let primitive = variable.primitive();

        let mut workspace = ScatterWorkspace::new(input.vacuum_wavenumber(), request, stack.len());

        let left_quantities = IsotropicLayerQuantities::new(stack.left_exterior(), input);

        let (_, mut current_admittance) =
            medium_second_jets(stack.left_exterior(), &left_quantities, input, primitive);

        for (index, layer) in stack.iter().enumerate() {
            let quantities = IsotropicLayerQuantities::new(layer.material(), input);

            let (kappa, layer_admittance) =
                medium_second_jets(layer.material(), &quantities, input, primitive);

            let interface = interface::<C, D, _>(&current_admittance, &layer_admittance);

            let exponent = second_propagation_exponent(
                &quantities,
                &kappa,
                layer.thickness().as_cm(),
                primitive,
                index,
            );

            let propagation = propagation_from_exponent::<C, D, _>(exponent);

            workspace.append_layer::<C, D>(interface, propagation);

            current_admittance = layer_admittance;
        }

        let right_quantities = IsotropicLayerQuantities::new(stack.right_exterior(), input);

        let (_, right_admittance) =
            medium_second_jets(stack.right_exterior(), &right_quantities, input, primitive);

        let final_interface = interface::<C, D, _>(&current_admittance, &right_admittance);

        workspace.append(final_interface);

        let mut total = workspace.into_total();

        if let Some(rule) = variable.chain_rule(input) {
            total = total.chain_rule(&rule);
        }

        Ok(total)
    }
}

/// Cut positions corresponding to the two boundaries of one finite layer.
///
/// A cut index `k` refers to the division:
///
/// ```text
/// components[..k] | components[k..]
/// ```
///
/// Thus:
///
/// - `left` is the cut immediately after the interface entering the layer;
/// - `right` is the cut immediately after propagation through the layer and
///   before the interface leaving it.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub(crate) struct LayerCutIndices {
    left: usize,
    right: usize,
}

impl LayerCutIndices {
    pub(crate) const fn new(left: usize, right: usize) -> Self {
        Self { left, right }
    }

    pub(crate) const fn left(self) -> usize {
        self.left
    }

    pub(crate) const fn right(self) -> usize {
        self.right
    }
}

/// Workspace used while constructing a scalar-channel scattering response.
///
/// `A` determines the derivative order carried by each scattering entry:
///
/// - sampled arrays for value-only evaluation;
/// - first-order jets for first derivatives;
/// - second-order jets for first and second derivatives.
///
/// The workspace always accumulates `total`. Individual components and layer
/// cut positions are retained only when internal fields were requested.
pub(crate) struct ScatterWorkspace<A> {
    total: ScatterEntries<A>,
    components: Option<Vec<ScatterEntries<A>>>,
    layer_cuts: Option<Vec<LayerCutIndices>>,
}

impl<A> ScatterWorkspace<A> {
    /// Return the accumulated scattering response.
    pub(crate) fn total(&self) -> &ScatterEntries<A> {
        &self.total
    }

    /// Consume the workspace and return the accumulated response.
    pub(crate) fn into_total(self) -> ScatterEntries<A> {
        self.total
    }

    /// Return retained physical components, when internal fields were
    /// requested.
    pub(crate) fn components(&self) -> Option<&[ScatterEntries<A>]> {
        self.components.as_deref()
    }

    /// Return finite-layer cut positions, when internal fields were requested.
    pub(crate) fn layer_cuts(&self) -> Option<&[LayerCutIndices]> {
        self.layer_cuts.as_deref()
    }

    /// Return the current cut index.
    ///
    /// The cut index equals the number of physical components appended so far.
    fn current_cut(&self) -> usize {
        self.components.as_ref().map_or(0, Vec::len)
    }

    pub(crate) fn new<C, D>(
        source: &ArrayBase<OwnedRepr<C>, D>,
        request: InternalFieldRequest,
        layer_count: usize,
    ) -> Self
    where
        C: ComplexScalar,
        D: Dimension,
        A: ScalarAlgebra<C, D>,
    {
        Self {
            total: ScatterEntries::identity_like(source),

            components: request.is_requested().then(|| {
                /*
                 * A stack with N finite layers contains:
                 *
                 * N propagation components
                 * N + 1 interface components
                 *
                 * for a total of 2N + 1 components.
                 */
                Vec::with_capacity(layer_count.saturating_mul(2).saturating_add(1))
            }),

            layer_cuts: request
                .is_requested()
                .then(|| Vec::with_capacity(layer_count)),
        }
    }

    /// Append one physical scattering component.
    ///
    /// The accumulated system represents the previous total followed
    /// geometrically by `component`.
    pub(crate) fn append<C, D>(&mut self, component: ScatterEntries<A>)
    where
        C: ComplexScalar,
        D: Dimension,
        A: ScalarAlgebra<C, D>,
    {
        self.total = cascade::<C, D, A>(&self.total, &component);

        if let Some(components) = &mut self.components {
            components.push(component);
        }
    }

    /// Record the cuts at the left and right boundaries of one finite layer.
    pub(crate) fn record_layer(&mut self, left_cut: usize, right_cut: usize) {
        let current_cut = self.current_cut();

        debug_assert!(left_cut <= right_cut);
        debug_assert!(
            right_cut <= current_cut,
            "layer cut lies beyond appended components",
        );

        if let Some(layer_cuts) = &mut self.layer_cuts {
            layer_cuts.push(LayerCutIndices::new(left_cut, right_cut));
        }
    }

    /// Append the interface entering a finite layer and its propagation
    /// component, then record the corresponding internal cuts.
    ///
    /// The sequence is:
    ///
    /// ```text
    /// previous medium
    ///     → interface
    ///     → left layer boundary cut
    ///     → propagation
    ///     → right layer boundary cut.
    /// ```
    pub(crate) fn append_layer<C, D>(
        &mut self,
        interface: ScatterEntries<A>,
        propagation: ScatterEntries<A>,
    ) where
        C: ComplexScalar,
        D: Dimension,
        A: ScalarAlgebra<C, D>,
    {
        self.append::<C, D>(interface);

        let left_cut = self.current_cut();

        self.append::<C, D>(propagation);

        let right_cut = self.current_cut();

        self.record_layer(left_cut, right_cut);
    }

    pub(crate) fn into_parts(self) -> ScatterWorkspaceParts<A> {
        ScatterWorkspaceParts {
            total: self.total,
            components: self.components,
            layer_cuts: self.layer_cuts,
        }
    }
}

pub(crate) struct ScatterWorkspaceParts<A> {
    pub(crate) total: ScatterEntries<A>,
    pub(crate) components: Option<Vec<ScatterEntries<A>>>,
    pub(crate) layer_cuts: Option<Vec<LayerCutIndices>>,
}

fn validate_derivative_variable<M, R>(
    stack: &Stack<M, R>,
    variable: DerivativeVariable,
) -> Result<(), Scatter2Error> {
    if let DerivativeVariable::Thickness(requested) = variable {
        let layer_count = stack.len();

        if requested >= layer_count {
            return Err(Scatter2Error::ThicknessLayerOutOfBounds {
                requested,
                layer_count,
            });
        }
    }

    Ok(())
}

fn first_propagation_exponent<C, D>(
    quantities: &IsotropicLayerQuantities<C, D>,
    kappa: &ArrayJetFirst<C, D>,
    thickness_cm: C::RealField,
    variable: DerivativeVariable,
    layer_index: usize,
) -> ArrayJetFirst<C, D>
where
    C: ComplexScalar,
    C::RealField: Copy,
    D: Dimension,
{
    let distance = C::from_real(thickness_cm);

    let coefficient = C::i() * distance;

    if matches!(
        variable,
        DerivativeVariable::Thickness(requested)
            if requested == layer_index
    ) {
        ArrayJetFirst::from_parts(
            quantities.kappa().clone() * coefficient,
            quantities.kappa().mapv(|kappa| C::i() * kappa),
        )
    } else {
        kappa.scale(coefficient)
    }
}

fn second_propagation_exponent<C, D>(
    quantities: &IsotropicLayerQuantities<C, D>,
    kappa: &ArrayJet<C, D>,
    thickness_cm: C::RealField,
    variable: DerivativeVariable,
    layer_index: usize,
) -> ArrayJet<C, D>
where
    C: ComplexScalar,
    C::RealField: Copy,
    D: Dimension,
{
    let distance = C::from_real(thickness_cm);

    let coefficient = C::i() * distance;

    if matches!(
        variable,
        DerivativeVariable::Thickness(requested)
            if requested == layer_index
    ) {
        ArrayJet::from_parts(
            quantities.kappa().clone() * coefficient,
            quantities.kappa().mapv(|kappa| C::i() * kappa),
            quantities.kappa().mapv(|_| C::zero()),
        )
    } else {
        kappa.scale(coefficient)
    }
}

/// Construct first-order normal-wavenumber and admittance jets for one medium.
///
/// `variable` must already be primitive. Thickness derivatives return constant
/// medium jets because material and admittance values have no explicit
/// thickness dependence.
fn medium_first_jets<M, C, D>(
    material: &M,
    quantities: &IsotropicLayerQuantities<C, D>,
    input: &PlanarInput<ArrayBase<OwnedRepr<C>, D>>,
    variable: DerivativeVariable,
) -> (ArrayJetFirst<C, D>, ArrayJetFirst<C, D>)
where
    M: Material<Real = C::RealField>,
    C: ComplexScalar,
    D: Dimension,
{
    match variable {
        DerivativeVariable::VacuumWavenumberSquared => {
            let derivatives = IsotropicLayerFirstDerivatives::vacuum_wavenumber_squared(
                material,
                quantities,
                input.vacuum_wavenumber(),
                input.polarisation(),
            );

            let kappa =
                ArrayJetFirst::from_parts(quantities.kappa().clone(), derivatives.dkappa().clone());

            let admittance =
                IsotropicLayerAdmittance::first_jet_from_quantities(quantities, &derivatives);

            (kappa, admittance)
        }

        DerivativeVariable::ParallelWavenumberSquared => {
            let derivatives =
                IsotropicLayerFirstDerivatives::parallel_wavenumber_squared(quantities);

            let kappa =
                ArrayJetFirst::from_parts(quantities.kappa().clone(), derivatives.dkappa().clone());

            let admittance =
                IsotropicLayerAdmittance::first_jet_from_quantities(quantities, &derivatives);

            (kappa, admittance)
        }

        DerivativeVariable::Thickness(_) => {
            let kappa = ArrayJetFirst::constant(quantities.kappa().clone());

            let admittance = ArrayJetFirst::constant(quantities.admittance().into_inner());

            (kappa, admittance)
        }

        DerivativeVariable::VacuumWavenumber | DerivativeVariable::ParallelWavenumber => {
            unreachable!("primitive() returned a linear derivative variable")
        }
    }
}

/// Construct second-order normal-wavenumber and admittance jets for one medium.
///
/// `variable` must already be primitive.
fn medium_second_jets<M, C, D>(
    material: &M,
    quantities: &IsotropicLayerQuantities<C, D>,
    input: &PlanarInput<ArrayBase<OwnedRepr<C>, D>>,
    variable: DerivativeVariable,
) -> (ArrayJet<C, D>, ArrayJet<C, D>)
where
    M: Material<Real = C::RealField>,
    C: ComplexScalar,
    D: Dimension,
{
    match variable {
        DerivativeVariable::VacuumWavenumberSquared => {
            let derivatives = IsotropicLayerSecondDerivatives::vacuum_wavenumber_squared(
                material,
                quantities,
                input.vacuum_wavenumber(),
                input.polarisation(),
            );

            let kappa = ArrayJet::from_parts(
                quantities.kappa().clone(),
                derivatives.first().dkappa().clone(),
                derivatives.ddkappa().clone(),
            );

            let admittance =
                IsotropicLayerAdmittance::second_jet_from_quantities(quantities, &derivatives);

            (kappa, admittance)
        }

        DerivativeVariable::ParallelWavenumberSquared => {
            let derivatives =
                IsotropicLayerSecondDerivatives::parallel_wavenumber_squared(quantities);

            let kappa = ArrayJet::from_parts(
                quantities.kappa().clone(),
                derivatives.first().dkappa().clone(),
                derivatives.ddkappa().clone(),
            );

            let admittance =
                IsotropicLayerAdmittance::second_jet_from_quantities(quantities, &derivatives);

            (kappa, admittance)
        }

        DerivativeVariable::Thickness(_) => {
            let kappa = ArrayJet::constant(quantities.kappa().clone());

            let admittance = ArrayJet::constant(quantities.admittance().into_inner());

            (kappa, admittance)
        }

        DerivativeVariable::VacuumWavenumber | DerivativeVariable::ParallelWavenumber => {
            unreachable!("primitive() returned a linear derivative variable")
        }
    }
}

pub(crate) fn reconstruct_scatter_fields<C, D, A>(
    workspace: &ScatterWorkspace<A>,
    incident_side: IncidentSide,
    source: &ArrayBase<OwnedRepr<C>, D>,
) -> Vec<LayerBoundaryWavesGeneric<A>>
where
    C: ComplexScalar,
    D: Dimension,
    A: ScalarAlgebra<C, D> + Clone,
{
    let components = workspace.components().expect(
        "scatter components are retained only when \
             internal fields are requested",
    );

    let layer_cuts = workspace.layer_cuts().expect(
        "layer cuts are retained only when \
             internal fields are requested",
    );

    let prefixes = prefix_cascades::<C, D, A>(components, source);

    let suffixes = suffix_cascades::<C, D, A>(components, source);

    /*
     * Incoming amplitudes are represented using the same algebra as the
     * scattering entries. For jets, both are constants: changing a stack or
     * spectral parameter does not change the imposed unit incident amplitude.
     */
    let zero = A::constant_like(source, C::zero());

    let one = A::constant_like(source, C::one());

    let (left_incoming, right_incoming) = match incident_side {
        IncidentSide::Left => (one, zero),

        IncidentSide::Right => (zero, one),
    };

    layer_cuts
        .iter()
        .map(|cuts| {
            let left_cut = cuts.left();
            let right_cut = cuts.right();

            let left = waves_at_cut::<C, D, A>(
                &prefixes[left_cut],
                &suffixes[left_cut],
                &left_incoming,
                &right_incoming,
            );

            let right = waves_at_cut::<C, D, A>(
                &prefixes[right_cut],
                &suffixes[right_cut],
                &left_incoming,
                &right_incoming,
            );

            LayerBoundaryWavesGeneric::new(left, right)
        })
        .collect()
}

fn prefix_cascades<C, D, A>(
    components: &[ScatterEntries<A>],
    source: &ArrayBase<OwnedRepr<C>, D>,
) -> Vec<ScatterEntries<A>>
where
    C: ComplexScalar,
    D: Dimension,
    A: ScalarAlgebra<C, D> + Clone,
{
    let mut prefixes = Vec::with_capacity(components.len() + 1);

    prefixes.push(ScatterEntries::identity_like(source));

    for component in components {
        let next = cascade::<C, D, A>(
            prefixes.last().expect("identity prefix was inserted"),
            component,
        );

        prefixes.push(next);
    }

    prefixes
}

fn suffix_cascades<C, D, A>(
    components: &[ScatterEntries<A>],
    source: &ArrayBase<OwnedRepr<C>, D>,
) -> Vec<ScatterEntries<A>>
where
    C: ComplexScalar,
    D: Dimension,
    A: ScalarAlgebra<C, D> + Clone,
{
    let component_count = components.len();

    let mut reversed = Vec::with_capacity(component_count + 1);

    reversed.push(ScatterEntries::identity_like(source));

    for component in components.iter().rev() {
        let next = cascade::<C, D, A>(
            component,
            reversed.last().expect("identity suffix was inserted"),
        );

        reversed.push(next);
    }

    reversed.reverse();
    reversed
}

fn waves_at_cut<C, D, A>(
    left: &ScatterEntries<A>,
    right: &ScatterEntries<A>,
    left_incoming: &A,
    right_incoming: &A,
) -> BidirectionalWavesGeneric<A>
where
    C: ComplexScalar,
    D: Dimension,
    A: ScalarAlgebra<C, D>,
{
    let one = A::constant_like(left.s11.value(), C::one());

    let denominator = one.subtract(&left.s22.multiply(&right.s11));

    let forward = left
        .s21
        .multiply(left_incoming)
        .add(&left.s22.multiply(&right.s12).multiply(right_incoming))
        .divide(&denominator);

    let backward = right
        .s11
        .multiply(&forward)
        .add(&right.s12.multiply(right_incoming));

    BidirectionalWavesGeneric::new(forward, backward)
}

#[cfg(test)]
mod tests {
    use approx::assert_relative_eq;
    use ndarray::{Array0, ArrayBase, Dimension, OwnedRepr, arr0, array};
    use num_complex::Complex64;

    use super::*;

    use crate::{
        ValidationConfig,
        backend::Polarisation,
        material::{Constant, enums::IsotropicMaterial},
        stack::Thickness,
    };

    type C = Complex64;

    fn c(value: f64) -> C {
        C::new(value, 0.0)
    }

    fn assert_complex_close(actual: C, expected: C, tolerance: f64) {
        assert_relative_eq!(
            actual.re,
            expected.re,
            epsilon = tolerance,
            max_relative = tolerance,
        );

        assert_relative_eq!(
            actual.im,
            expected.im,
            epsilon = tolerance,
            max_relative = tolerance,
        );
    }

    fn assert_array_close<D>(
        actual: &ArrayBase<OwnedRepr<C>, D>,
        expected: &ArrayBase<OwnedRepr<C>, D>,
        tolerance: f64,
    ) where
        D: Dimension,
    {
        assert_eq!(actual.raw_dim(), expected.raw_dim());

        for (&actual, &expected) in actual.iter().zip(expected.iter()) {
            assert_complex_close(actual, expected, tolerance);
        }
    }

    fn assert_matrix_close<D>(
        actual: &ScatterMatrix2<C, D>,
        expected: &ScatterMatrix2<C, D>,
        tolerance: f64,
    ) where
        D: Dimension,
    {
        assert_array_close(actual.s11(), expected.s11(), tolerance);

        assert_array_close(actual.s12(), expected.s12(), tolerance);

        assert_array_close(actual.s21(), expected.s21(), tolerance);

        assert_array_close(actual.s22(), expected.s22(), tolerance);
    }

    fn planar(
        vacuum_wavenumber: f64,
        parallel_wavenumber: f64,
        polarisation: Polarisation,
    ) -> PlanarInput<Array0<C>> {
        PlanarInput::new(
            arr0(c(vacuum_wavenumber)),
            arr0(c(parallel_wavenumber)),
            polarisation,
        )
    }

    fn empty_stack(left_epsilon: f64, right_epsilon: f64) -> Stack<IsotropicMaterial<f64>, f64> {
        Stack::builder(
            Constant::new(left_epsilon, 1.0),
            Constant::new(right_epsilon, 1.0),
        )
        .validation(ValidationConfig::permissive())
        .build()
        .unwrap()
    }

    fn one_layer_stack(thickness_cm: f64) -> Stack<IsotropicMaterial<f64>, f64> {
        Stack::builder(Constant::new(1.0, 1.0), Constant::new(1.44, 1.0))
            .with_layer(
                Constant::new(2.25, 1.0),
                Thickness::from_cm(thickness_cm).unwrap(),
            )
            .validation(ValidationConfig::permissive())
            .build()
            .unwrap()
    }

    fn two_layer_stack(
        first_thickness_cm: f64,
        second_thickness_cm: f64,
    ) -> Stack<IsotropicMaterial<f64>, f64> {
        Stack::builder(Constant::new(1.0, 1.0), Constant::new(1.44, 1.0))
            .with_layer(
                Constant::new(2.25, 1.0),
                Thickness::from_cm(first_thickness_cm).unwrap(),
            )
            .with_layer(
                Constant::new(3.24, 1.0),
                Thickness::from_cm(second_thickness_cm).unwrap(),
            )
            .build()
            .unwrap()
    }

    #[test]
    fn empty_stack_is_direct_exterior_interface() {
        let stack = empty_stack(1.0, 2.25);

        let input = planar(3.0, 0.0, Polarisation::TransverseElectric);

        let matrix = Scatter2::new()
            .evaluate(&stack, &input, InternalFieldRequest::None)
            .unwrap();

        let denominator = 1.0 + 1.5;

        assert_complex_close(matrix.s11()[()], c((1.0 - 1.5) / denominator), 1e-12);

        assert_complex_close(matrix.s21()[()], c(2.0 / denominator), 1e-12);

        assert_complex_close(matrix.s12()[()], c(3.0 / denominator), 1e-12);

        assert_complex_close(matrix.s22()[()], c((1.5 - 1.0) / denominator), 1e-12);
    }

    #[test]
    fn equal_exterior_media_and_empty_stack_are_transparent() {
        let stack = empty_stack(1.0, 1.0);

        let input = planar(3.0, 0.4, Polarisation::TransverseMagnetic);

        let matrix = Scatter2::new()
            .evaluate(&stack, &input, InternalFieldRequest::None)
            .unwrap();

        assert_complex_close(matrix.s11()[()], c(0.0), 1e-12);

        assert_complex_close(matrix.s12()[()], c(1.0), 1e-12);

        assert_complex_close(matrix.s21()[()], c(1.0), 1e-12);

        assert_complex_close(matrix.s22()[()], c(0.0), 1e-12);
    }

    #[test]
    fn uniform_layer_has_zero_reflection_and_propagation_phase() {
        let medium = Constant::new(2.25, 1.0);

        let thickness_cm = 0.3;

        let stack = Stack::builder(medium.clone(), medium)
            .with_layer(medium.clone(), Thickness::from_cm(thickness_cm).unwrap())
            .build()
            .unwrap();

        let input = planar(3.0, 0.4, Polarisation::TransverseElectric);

        let matrix = Scatter2::new()
            .evaluate(&stack, &input, InternalFieldRequest::None)
            .unwrap();

        let kappa = (2.25 * 3.0_f64.powi(2) - 0.4_f64.powi(2)).sqrt();

        let phase = (C::i() * c(kappa * thickness_cm)).exp();

        assert_complex_close(matrix.s11()[()], c(0.0), 1e-12);

        assert_complex_close(matrix.s22()[()], c(0.0), 1e-12);

        assert_complex_close(matrix.s21()[()], phase, 1e-12);

        assert_complex_close(matrix.s12()[()], phase, 1e-12);
    }

    #[test]
    fn zero_thickness_layer_equals_two_adjacent_interfaces() {
        let stack = one_layer_stack(0.0);

        let input = planar(3.0, 0.4, Polarisation::TransverseElectric);

        let with_layer = Scatter2::new()
            .evaluate(&stack, &input, InternalFieldRequest::None)
            .unwrap();

        /*
         * A zero-thickness intermediate layer should algebraically collapse to
         * the direct exterior interface.
         */
        let direct = empty_stack(1.0, 1.44);

        let without_layer = Scatter2::new()
            .evaluate(&direct, &input, InternalFieldRequest::None)
            .unwrap();

        assert_matrix_close(&with_layer, &without_layer, 1e-12);
    }

    #[test]
    fn asymmetric_layer_order_changes_scattering_response() {
        let first = two_layer_stack(0.17, 0.29);

        let reversed = Stack::builder(Constant::new(1.0, 1.0), Constant::new(1.44, 1.0))
            .with_layer(Constant::new(3.24, 1.0), Thickness::from_cm(0.29).unwrap())
            .with_layer(Constant::new(2.25, 1.0), Thickness::from_cm(0.17).unwrap())
            .build()
            .unwrap();

        let input = planar(3.0, 0.4, Polarisation::TransverseElectric);

        let first = Scatter2::new()
            .evaluate(&first, &input, InternalFieldRequest::None)
            .unwrap();

        let reversed = Scatter2::new()
            .evaluate(&reversed, &input, InternalFieldRequest::None)
            .unwrap();

        assert_ne!(first.s11(), reversed.s11());
    }

    #[test]
    fn thickness_first_derivative_matches_finite_difference() {
        let d0 = 0.17;
        let d1 = 0.29;
        let h = 1e-6;

        let input = planar(3.0, 0.4, Polarisation::TransverseElectric);

        let analytic = Scatter2::new()
            .evaluate_first(
                &two_layer_stack(d0, d1),
                &input,
                DerivativeVariable::Thickness(0),
                InternalFieldRequest::None,
            )
            .unwrap();

        let plus = Scatter2::new()
            .evaluate(
                &two_layer_stack(d0 + h, d1),
                &input,
                InternalFieldRequest::None,
            )
            .unwrap();

        let minus = Scatter2::new()
            .evaluate(
                &two_layer_stack(d0 - h, d1),
                &input,
                InternalFieldRequest::None,
            )
            .unwrap();

        assert_complex_close(
            analytic.s11.first()[()],
            (plus.s11()[()] - minus.s11()[()]) / (2.0 * h),
            2e-7,
        );

        assert_complex_close(
            analytic.s12.first()[()],
            (plus.s12()[()] - minus.s12()[()]) / (2.0 * h),
            2e-7,
        );

        assert_complex_close(
            analytic.s21.first()[()],
            (plus.s21()[()] - minus.s21()[()]) / (2.0 * h),
            2e-7,
        );

        assert_complex_close(
            analytic.s22.first()[()],
            (plus.s22()[()] - minus.s22()[()]) / (2.0 * h),
            2e-7,
        );
    }

    #[test]
    fn thickness_second_derivative_matches_finite_difference() {
        let d0 = 0.17;
        let d1 = 0.29;
        let h = 1e-4;

        let input = planar(3.0, 0.4, Polarisation::TransverseMagnetic);

        let analytic = Scatter2::new()
            .evaluate_second(
                &two_layer_stack(d0, d1),
                &input,
                DerivativeVariable::Thickness(1),
                InternalFieldRequest::None,
            )
            .unwrap();

        let plus = Scatter2::new()
            .evaluate(
                &two_layer_stack(d0, d1 + h),
                &input,
                InternalFieldRequest::None,
            )
            .unwrap();

        let zero = Scatter2::new()
            .evaluate(&two_layer_stack(d0, d1), &input, InternalFieldRequest::None)
            .unwrap();

        let minus = Scatter2::new()
            .evaluate(
                &two_layer_stack(d0, d1 - h),
                &input,
                InternalFieldRequest::None,
            )
            .unwrap();

        let h2 = h * h;

        assert_complex_close(
            analytic.s11.second()[()],
            (plus.s11()[()] - c(2.0) * zero.s11()[()] + minus.s11()[()]) / h2,
            3e-6,
        );

        assert_complex_close(
            analytic.s21.second()[()],
            (plus.s21()[()] - c(2.0) * zero.s21()[()] + minus.s21()[()]) / h2,
            3e-6,
        );
    }

    #[test]
    fn linear_vacuum_wavenumber_derivative_matches_finite_difference() {
        let stack = two_layer_stack(0.17, 0.29);

        let k0 = 3.0;
        let h = 1e-6;

        let input = planar(k0, 0.4, Polarisation::TransverseElectric);

        let analytic = Scatter2::new()
            .evaluate_first(
                &stack,
                &input,
                DerivativeVariable::VacuumWavenumber,
                InternalFieldRequest::None,
            )
            .unwrap();

        let plus_input = planar(k0 + h, 0.4, Polarisation::TransverseElectric);

        let minus_input = planar(k0 - h, 0.4, Polarisation::TransverseElectric);

        let plus = Scatter2::new()
            .evaluate(&stack, &plus_input, InternalFieldRequest::None)
            .unwrap();

        let minus = Scatter2::new()
            .evaluate(&stack, &minus_input, InternalFieldRequest::None)
            .unwrap();

        assert_complex_close(
            analytic.s11.first()[()],
            (plus.s11()[()] - minus.s11()[()]) / (2.0 * h),
            3e-7,
        );

        assert_complex_close(
            analytic.s21.first()[()],
            (plus.s21()[()] - minus.s21()[()]) / (2.0 * h),
            3e-7,
        );
    }

    #[test]
    fn parallel_wavenumber_squared_second_derivative_matches_finite_difference() {
        let stack = two_layer_stack(0.17, 0.29);

        let parallel_squared = 0.16_f64;
        let h = 1e-4;

        let input = planar(
            3.0,
            parallel_squared.sqrt(),
            Polarisation::TransverseMagnetic,
        );

        let analytic = Scatter2::new()
            .evaluate_second(
                &stack,
                &input,
                DerivativeVariable::ParallelWavenumberSquared,
                InternalFieldRequest::None,
            )
            .unwrap();

        let plus_input = planar(
            3.0,
            (parallel_squared + h).sqrt(),
            Polarisation::TransverseMagnetic,
        );

        let zero_input = planar(
            3.0,
            parallel_squared.sqrt(),
            Polarisation::TransverseMagnetic,
        );

        let minus_input = planar(
            3.0,
            (parallel_squared - h).sqrt(),
            Polarisation::TransverseMagnetic,
        );

        let plus = Scatter2::new()
            .evaluate(&stack, &plus_input, InternalFieldRequest::None)
            .unwrap();

        let zero = Scatter2::new()
            .evaluate(&stack, &zero_input, InternalFieldRequest::None)
            .unwrap();

        let minus = Scatter2::new()
            .evaluate(&stack, &minus_input, InternalFieldRequest::None)
            .unwrap();

        let h2 = h * h;

        assert_complex_close(
            analytic.s11.second()[()],
            (plus.s11()[()] - c(2.0) * zero.s11()[()] + minus.s11()[()]) / h2,
            4e-6,
        );

        assert_complex_close(
            analytic.s21.second()[()],
            (plus.s21()[()] - c(2.0) * zero.s21()[()] + minus.s21()[()]) / h2,
            4e-6,
        );
    }

    #[test]
    fn invalid_thickness_index_returns_error() {
        let stack = one_layer_stack(0.2);

        let input = planar(3.0, 0.4, Polarisation::TransverseElectric);

        let error = Scatter2::new()
            .evaluate_first(
                &stack,
                &input,
                DerivativeVariable::Thickness(1),
                InternalFieldRequest::None,
            )
            .unwrap_err();

        assert_eq!(
            error,
            Scatter2Error::ThicknessLayerOutOfBounds {
                requested: 1,
                layer_count: 1,
            },
        );
    }

    #[test]
    fn sampled_input_shape_is_preserved() {
        let stack = one_layer_stack(0.2);

        let input = PlanarInput::new(
            array![c(2.0), c(2.5), c(3.0)],
            array![c(0.2), c(0.3), c(0.4)],
            Polarisation::TransverseElectric,
        );

        let result = Scatter2::new()
            .evaluate_second(
                &stack,
                &input,
                DerivativeVariable::VacuumWavenumber,
                InternalFieldRequest::None,
            )
            .unwrap();

        let expected = input.vacuum_wavenumber().raw_dim();

        for entry in [&result.s11, &result.s12, &result.s21, &result.s22] {
            assert_eq!(entry.value().raw_dim(), expected);
            assert_eq!(entry.first().raw_dim(), expected);
            assert_eq!(entry.second().raw_dim(), expected);
        }
    }
}
